"""Document export helpers."""

import re
from datetime import datetime
from pathlib import Path
from typing import Any


def _slugify(value: str, max_length: int = 80) -> str:
    slug = re.sub(r"[^\w\u4e00-\u9fff-]+", "-", value.strip().lower(), flags=re.UNICODE)
    slug = re.sub(r"-+", "-", slug).strip("-")
    return (slug or "document")[:max_length].strip("-") or "document"


def _timestamp() -> str:
    return datetime.now().strftime("%Y%m%d-%H%M%S")


def export_markdown(
    markdown: str,
    output_dir: Path | str = "./outputs",
    title: str = "document",
) -> Path:
    """Export markdown content to a timestamped file."""

    output_path = Path(output_dir) / f"{_timestamp()}-{_slugify(title)}.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(markdown, encoding="utf-8")
    return output_path


def _strip_inline_markdown(text: str) -> str:
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
    text = re.sub(r"`([^`]*)`", r"\1", text)
    return text


def _is_table_separator(line: str) -> bool:
    stripped = line.strip()
    return bool(re.fullmatch(r"\|?[\s:|-]+\|?", stripped)) and "-" in stripped


def _parse_table(lines: list[str]) -> list[list[str]]:
    rows: list[list[str]] = []
    for line in lines:
        if _is_table_separator(line):
            continue
        cells = [cell.strip() for cell in line.strip().strip("|").split("|")]
        rows.append(cells)
    return rows


def _add_table(document: Any, lines: list[str]) -> None:
    rows = _parse_table(lines)
    if not rows:
        return
    column_count = max(len(row) for row in rows)
    table = document.add_table(rows=0, cols=column_count)
    table.style = "Table Grid"
    for row_values in rows:
        cells = table.add_row().cells
        for index, value in enumerate(row_values):
            cells[index].text = _strip_inline_markdown(value)


def markdown_to_docx(markdown: str, document: Any) -> None:
    """Append markdown content to an existing python-docx document."""

    table_buffer: list[str] = []
    for line in markdown.splitlines():
        stripped = line.strip()
        if "|" in stripped and stripped.startswith("|"):
            table_buffer.append(stripped)
            continue
        if table_buffer:
            _add_table(document, table_buffer)
            table_buffer = []

        if not stripped:
            continue
        if stripped.startswith("### "):
            document.add_heading(_strip_inline_markdown(stripped[4:]), level=3)
        elif stripped.startswith("## "):
            document.add_heading(_strip_inline_markdown(stripped[3:]), level=2)
        elif stripped.startswith("# "):
            document.add_heading(_strip_inline_markdown(stripped[2:]), level=1)
        elif re.match(r"^[-*]\s+", stripped):
            document.add_paragraph(_strip_inline_markdown(stripped[2:]), style="List Bullet")
        elif re.match(r"^\d+[.)]\s+", stripped):
            text = re.sub(r"^\d+[.)]\s+", "", stripped)
            document.add_paragraph(_strip_inline_markdown(text), style="List Number")
        else:
            document.add_paragraph(_strip_inline_markdown(stripped))

    if table_buffer:
        _add_table(document, table_buffer)


def _set_header_footer(document: Any, title: str) -> None:
    section = document.sections[0]
    section.header.paragraphs[0].text = title
    section.footer.paragraphs[0].text = "Generated by writing-agent"


def export_docx(
    markdown: str,
    output_dir: Path | str = "./outputs",
    title: str = "document",
    metadata: dict[str, Any] | None = None,
) -> Path:
    """Export a formatted docx version of markdown content."""

    try:
        from docx import Document
    except ImportError as exc:  # pragma: no cover - dependency guard
        raise RuntimeError("Install python-docx to export .docx files.") from exc

    metadata = metadata or {}
    generated_at = metadata.get("generated_at") or datetime.now().isoformat(timespec="seconds")
    output_path = Path(output_dir) / f"{_timestamp()}-{_slugify(title)}.docx"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    document = Document()
    _set_header_footer(document, title)
    document.add_heading(title, level=0)
    document.add_paragraph(f"Document type: {metadata.get('document_type', '')}")
    document.add_paragraph(f"Generated at: {generated_at}")
    document.add_paragraph(f"Topic: {metadata.get('topic', title)}")
    document.add_paragraph(f"Audience: {metadata.get('audience', '')}")
    document.add_page_break()

    document.add_heading("生成说明", level=1)
    document.add_paragraph(f"Model: {metadata.get('model_name', '')}")
    document.add_paragraph(f"RAG mode: {metadata.get('rag_mode', '')}")
    document.add_paragraph(f"Collection: {metadata.get('collection', '')}")
    document.add_paragraph(f"Thread ID: {metadata.get('thread_id', '')}")
    document.add_paragraph(f"Generated at: {generated_at}")
    document.add_page_break()

    markdown_to_docx(markdown, document)
    document.save(str(output_path))
    return output_path
